In [1]:
from portfolio.acct import TradingAcct, accountSetup
from portfolio.pos import Position
# import importlib

In [2]:
    # Init Account with Alpaca data
    trade_account = accountSetup()
    if trade_account is None: 
        print("Error in account setup")

In [3]:
trade_account.positions.get('SPY').history

     timestamp    open      high       low   close      volume
0   2025-05-01  560.37  564.0699  557.8600  558.47  63186146.0
1   2025-05-02  564.73  568.3800  562.3800  566.76  60717270.0
2   2025-05-05  562.57  566.6500  561.7000  563.51  38659222.0
3   2025-05-06  557.93  563.3476  556.9600  558.80  48264708.0
4   2025-05-07  560.15  563.8200  556.0400  561.15  55733229.0
5   2025-05-08  565.24  570.3100  561.7000  565.06  65130787.0
6   2025-05-09  566.48  567.5000  562.7637  564.34  37603427.0
7   2025-05-12  581.47  583.0000  577.0400  582.99  78993570.0
8   2025-05-13  583.41  589.0800  582.8400  586.84  67947225.0
9   2025-05-14  587.81  588.9800  585.5350  587.59  66283531.0
10  2025-05-15  585.56  590.9700  585.0969  590.46  71268145.0
11  2025-05-16  591.25  594.5000  589.2800  594.20  76052101.0
12  2025-05-19  588.10  595.5400  588.1000  594.85  68168509.0
13  2025-05-20  593.09  594.0500  589.6000  592.85  60614492.0
14  2025-05-21  588.44  592.5800  581.8200  582.86  96023782.0

In [9]:
    # print("bp:",trade_account.buying_power)
    # print("portfolio value:",trade_account.portfolio_value)
    
    for key, value in trade_account.positions.items():
        print(value.total_value, key)

404.18 AAPL
582.86 SPY
334.62 TSLA